baseURL                 = "https://omn0mn0m.com/"  # Your domain name. Must end with "/"
theme                   = "hugo-theme-omn0mn0m"
DefaultContentLanguage  = "en"                     # Default language for multilingual sites
# Metadata
title                   = "omn0mn0m"



# disqusshortname        = ""                      # https://gohugo.io/content-management/comments
# googleAnalytics        = ""                      # https://gohugo.io/templates/internal/#google-analytics
ignoreFiles             = [ "\\.#" ]

[permalinks]
  blog                  = '/:filename/'

[params]
  description             = 'Engineer LARPing as a medical student.'
  tagline                 = 'Engineer LARPing as a Med Student'
  images                  = ['/img/profile.png']
